name: Chunky
main: com.dumptruckman.chunky.Chunky
version: ${project.version}-b${build.number}
author: dumptruckman, SwearWord

commands:
  chunky:
    aliases: c

permissions:
    chunky.build_anywhere:
        description: Allows building anywhere.
        default: op
    chunky.no_chunk_limit:
        description: Allows building anywhere.
        default: op
    chunky.claim:
        description: Allows players to claim chunks.
        default: true
    chunky.unclaim:
        description: Allows players to unclaim chunks.
        default: true
    chunky.enabled:
        description: Allows this player to be affected by Chunky whatsoever.
        default: true
    chunky.adminunclaim:
        description: Allows players to unclaim anyone's chunk.
        default: op