name: Chunky
main: org.getchunky.chunky.Chunky
version: ${project.version}-b${build.number}
author: dumptruckman, SwearWord
website: http://build.blockface.org

commands:
  chunky:
    aliases: c

permissions:
    chunky.claim:
        description: Allows players to claim chunks.
        default: true
    chunky.unclaim:
        description: Allows players to unclaim chunks.
        default: true
    chunky.admin.unclaim:
        description: Allows players to unclaim anyone's chunk.
        default: op
    chunky.admin.setperm:
        description: Allows players to set permissions in anyone's chunk.
        default: op
    chunky.admin.modify:
        description: Allows building/destroying anywhere.
        default: op
    chunky.admin.unlimited:
        description: Unlimited chunk claiming.
        default: op
    chunky.admin.command:
        description: Allows use of /chunky admin and it's sub-commands.
        default: op